# Generated by Django 5.2 on 2025-07-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
