# Generated by Django 5.2 on 2025-07-08 22:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_body_alter_homepage_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='rtfbody',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Тело страницы'),
        ),
    ]
